### ISSUE TITLE
Little spider game logic error

### ISSUE THREAD

**Issue by Bett-A-Fish** [oddstream/lsol#3]
Had a problem when playing Little Spider. I had been able to play a couple games previously just fine, but this one only allowed me to place black aces and kings.

![Screenshot_20220721-012359](https://user-images.githubusercontent.com/8015067/180649724-907615b0-5a78-4fec-bcc4-27453423d853.jpg)
g

**Comment by oddstream** [comment]
... it's even worse than that; the red-black ace-king logic was so bad, and so misplaced, that undo was broken too, as well as starting a new game.

New logic has been applied and will debut in version 22.
