### ISSUE TITLE
Mobile app ignores device rotation settings

### ISSUE THREAD

**Issue by Bett-A-Fish** [oddstream/lsol#4]
When using the mobile app with device settings locked to portrait, the app still rotates. 

I'm not familiar with what kinds of things require permissions to access. So I think the best thing would be to have a setting in game for locking screen orientation to portrait or landscape.

This seemed relevant:
https://github.com/love2d/love-android/issues/175
Though it is for love-android which I'm not sure is used here? but it is a port of love2d, so I think something similar would be usable.

**Comment by oddstream** [comment]
Tried adding a 'lockRotation' setting that causes love.displayrotated() to take no action, but it seems in LÖVE this function is called after a rotation has taken place, so the lockRotation setting has no effect.

**Comment by Bett-A-Fish** [comment]
I found this but it looks like it's how to lock the rotation in general rather than by user setting.
https://love2d.org/forums/viewtopic.php?t=92177

do you use [love-android](https://github.com/love2d/love-android)?

(I'm not familiar with lua or love, so idk how much help I'll manage to be here)

**Comment by oddstream** [comment]
Don't use love-android, because it's a version behind the main version of LÖVE.

Working on a way of doing this that doesn't require the dreaded 'requires restart', with 'Lock portrait' and 'Lock landscape' settings.

**Comment by oddstream** [comment]
Since (I don't think) LÖVE can read Android system settings, I've added an 'Allow orientation' setting that will fix the orientation to whatever-it-was when the app starts. It achieves this by doing a cheeky app restart behind the scenes.
